# Site Settings
title: "ActiveDocs"
logo: "/assets/images/adlogo.png"
subtitle: ""
name: "ActiveDocs"
description: "ActiveDocs developer and designer documentation."
url: "https://martinsrubarad.github.io"
baseurl: "/addev"
repository: "martinsrubarad/addev"

atom_feed:
  hide: true

# Theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Build Settings
markdown: kramdown

# Reading Files
include:
  - _pages

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-remote-theme

# Pagination
paginate: 5
paginate_path: /page:num/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: false
      share: false
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
